# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlInjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=1000)),
                ('target_url', models.URLField(max_length=1000, unique=True)),
                ('scan_status', models.CharField(max_length=1000)),
                ('scan_data', models.CharField(max_length=1000)),
                ('scan_log', models.CharField(max_length=1000)),
                ('vulnerable', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('-vulnerable',),
            },
        ),
    ]
