# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqliscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlinjection',
            options={'ordering': ('-vulnerability',)},
        ),
        migrations.RenameField(
            model_name='sqlinjection',
            old_name='vulnerable',
            new_name='vulnerability',
        ),
    ]
