# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqliscan', '0002_auto_20170102_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlinjection',
            name='target_urls',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sqlinjection',
            name='task_id',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='\u4efb\u52a1id'),
        ),
    ]
