# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqliscan', '0003_auto_20170112_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_urls', models.TextField(null=True)),
            ],
        ),
    ]
