# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqliscan', '0005_remove_sqlinjection_target_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_num', models.IntegerField(default=2)),
            ],
        ),
    ]
